// const xlsxj = require("xlsx-to-json");
// xlsxj(
//   {
//     input: "Sample Data.xlsx",
//     output: null,
//     sheet: "Sheet 1",
//   },
//   function (err, result) {
//     if (err) {
//       console.error(err);
//     } else {
//       console.log(result);
//     }
//   }
// );

const js2xmlparser = require("js2xmlparser");

demoJson = [
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "John Smith",
    Date: "5/6/21",
    Type: "Occupational Therapist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "10/23/36",
    "Account: Gender": "Male",
    Address: "161 Sussex St, Sydney, NSW 2001",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Toby Jones",
    Date: "5/14/21",
    Type: "Occupational Therapist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "7/21/30",
    "Account: Gender": "Male",
    Address: "14 The Avenue, North Sydney, NSW 2060",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Alex White",
    Date: "5/3/21",
    Type: "Occupational Therapist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "Private",
    "Account: Birthdate": "9/13/28",
    "Account: Gender": "Male",
    Address: "233 Macquarie St, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Ed James",
    Date: "5/10/21",
    Type: "Occupational Therapist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "Private",
    "Account: Birthdate": "5/31/32",
    "Account: Gender": "Male",
    Address: "50 Park St, Sydney, NSW 2000",
    "Account: Country of Birth": "England",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type": "Private residence - private rental",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Don Lyon",
    Date: "5/20/21",
    Type: "Podiatrist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "12/12/38",
    "Account: Gender": "Male",
    Address: "123 Sussex St, Sydney, NSW 2001",
    "Account: Country of Birth": "New Zealand",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type": "Private residence - private rental",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Peter Miller",
    Date: "5/20/21",
    Type: "Podiatrist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "10/30/32",
    "Account: Gender": "Male",
    Address: "55 King St, Sydney, NSW 2001",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Private residence - private rental",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Ryan Webster",
    Date: "5/19/21",
    Type: "Podiatrist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "Private",
    "Account: Birthdate": "9/21/40",
    "Account: Gender": "Male",
    Address: "100 Gloucester St, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Andrew Kim",
    Date: "5/12/21",
    Type: "Podiatrist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "Private",
    "Account: Birthdate": "9/13/28",
    "Account: Gender": "Male",
    Address: "2 Hampden St, North Sydney, NSW 2060",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Hugh Boyce",
    Date: "5/12/21",
    Type: "Occupational Therapist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CDMP",
    "Account: Birthdate": "2/12/40",
    "Account: Gender": "Male",
    Address: "4 Walker St, North Sydney, NSW 2060",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Michael Caldwell",
    Date: "5/11/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "Private",
    "Account: Birthdate": "7/29/36",
    "Account: Gender": "Male",
    Address: "35 Wentworth Ave, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Group (unrelated adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Jane Doe",
    Date: "5/31/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "7/12/34",
    "Account: Gender": "Female",
    Address: "15 Young St, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Mary Adams",
    Date: "5/14/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "10/17/47",
    "Account: Gender": "Female",
    Address: "342 Elizabeth St, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Kay Morris",
    Date: "5/13/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Multi-pack",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "6/16/38",
    "Account: Gender": "Female",
    Address: "27 Wentworth Ave, Sydney, NSW 2001",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Judy Grey",
    Date: "5/24/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "Private",
    "Account: Birthdate": "8/12/38",
    "Account: Gender": "Female",
    Address: "2 Hampden St, North Sydney, NSW 2060",
    "Account: Country of Birth": "England",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Cheryl Kramer",
    Date: "5/31/21",
    Type: "Exercise Physiologist",
    Hours: "",
    "Consult Type": "Multi-pack",
    "Account: Account Type": "Private",
    "Account: Birthdate": "10/23/36",
    "Account: Gender": "Female",
    Address: "67 Neutral St, North Sydney, NSW 2060",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Mavis Bird",
    Date: "5/13/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "Private",
    "Account: Birthdate": "10/23/36",
    "Account: Gender": "Female",
    Address: "3/ 19 Hunter St, Sydney, NSW 2000",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Pat Reese",
    Date: "5/27/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "11/19/46",
    "Account: Gender": "Female",
    Address: "100 Elizabeth Bay Rd, Elizabeth Bay, NSW 2011",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Fay Eaton",
    Date: "5/28/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "7/29/41",
    "Account: Gender": "Female",
    Address: "32 Garners Ave, Marrickville, NSW 2204",
    "Account: Country of Birth": "New Zealand",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Alice Beach",
    Date: "5/21/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Multi-pack",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "5/6/38",
    "Account: Gender": "Female",
    Address: "6 Young St, Redfern, NSW 2016",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Mary Friedman",
    Date: "5/27/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "Private",
    "Account: Birthdate": "10/23/36",
    "Account: Gender": "Female",
    Address: "42 Ridge St, Surry Hills, NSW 2010",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Wayne Moody",
    Date: "5/12/21",
    Type: "Physiotherapist",
    Hours: "",
    "Consult Type": "Multi-pack",
    "Account: Account Type": "Private",
    "Account: Birthdate": "9/17/29",
    "Account: Gender": "Male",
    Address: "84 Probert St, Newtown NSW 2042",
    "Account: Country of Birth": "United States",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Karen Xue",
    Date: "5/6/21",
    Type: "Social Support Individual",
    Hours: "2",
    "Consult Type": "Accompanied Activity",
    "Account: Account Type": "",
    "Account: Birthdate": "10/27/29",
    "Account: Gender": "Female",
    Address: "128 Salisbury Rd, Camperdown NSW 2050",
    "Account: Country of Birth": "China",
    "Account: Primary Language": "Mandarin",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type": "Not stated",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "Yes",
    "Account: Account Name": "Alison Peterson",
    Date: "5/4/21",
    Type: "Social Support Individual",
    Hours: "0:15",
    "Consult Type": "Telephone/Web Contact",
    "Account: Account Type": "",
    "Account: Birthdate": "7/21/30",
    "Account: Gender": "Female",
    Address: "7 Warwick St, Stanmore NSW 2048",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Mark Keller",
    Date: "5/20/21",
    Type: "Dietician",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "5/2/31",
    "Account: Gender": "Male",
    Address: "22 Jarrett St, Leichhardt NSW 2040",
    "Account: Country of Birth": "Canada",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "None",
    "Account: Accommodation Type": "Private residence - private rental",
    "Account: Household Composition": "Single (person living alone)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Amber Jones",
    Date: "5/12/21",
    Type: "Dietician",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "CHSP",
    "Account: Birthdate": "8/24/31",
    "Account: Gender": "Female",
    Address: "113 Hawthorne Parade, Haberfield NSW 2045",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "None",
    "Account: Accommodation Type": "Private residence - private rental",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Ella Rollins",
    Date: "5/3/21",
    Type: "Dietician",
    Hours: "",
    "Consult Type": "Initial",
    "Account: Account Type": "Private",
    "Account: Birthdate": "9/15/31",
    "Account: Gender": "Female",
    Address: "17 Augusta St, Five Dock NSW 2046",
    "Account: Country of Birth": "Australia",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "No",
    "Account: Disability": "Not stated/Inadequately described",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Couple",
    "Account: DVA Card Status": "No DVA entitlement",
  },
  {
    "Account: Existence of Carer": "No",
    "Account: Account Name": "Bill Whittle",
    Date: "5/18/21",
    Type: "Dietician",
    Hours: "",
    "Consult Type": "Standard",
    "Account: Account Type": "Private",
    "Account: Birthdate": "11/8/31",
    "Account: Gender": "Male",
    Address: "10 Byrnes St, Rozelle NSW 2039",
    "Account: Country of Birth": "England",
    "Account: Primary Language": "English",
    "Account: ATSI Origin": "Not stated/Inadequately described",
    "Account: Disability": "None",
    "Account: Accommodation Type":
      "Private residence - client or family owned/purchasing",
    "Account: Household Composition": "Group (related adults)",
    "Account: DVA Card Status": "No DVA entitlement",
  },
];

// console.log(typeof demoJson);
// console.log(Object.values(demoJson));

let finalJson = [];

let tempDataSet = { Account: {} };
demoJson.forEach((elements) => {
  //   //   console.log(elements);
  Object.keys(elements).forEach((element) => {
    // console.log(element);
    // console.log(element + ":" + elements[element]);
    // console.log(typeof element);
    if (element.includes("Account:")) {
      tempDataSet.Account[element.replace("Account:", "").trim()] =
        elements[element];
      //   console.log(element);
      //   console.log(1);
      //   // console.log(demoJson[element]);
    } else {
      tempDataSet[element] = elements[element];
      //   console.log(element);
      //   console.log(2);
    }
    // console.log(3);
    // console.log(tempDataSet);
  });
  //   console.log(tempDataSet);
  //   console.log(4);
  finalJson.push(tempDataSet);
});
// console.log(typeof finalJson);
console.log(finalJson);

// finalJson = JSON.parse({ finalJson });

//JOI VALIDATION FOR JSON
// function validator(obj) {
//   console.log(obj);
// }

//JSON to XML
// finalJson.forEach((elements) => {
//   console.log(JSON.stringify(elements));
//   //   elements.forEach((element) => {
//   //     console.log(js2xmlparser.parse("testXML", JSON.stringify(element)));
//   //   });
//   //   console.log(js2xmlparser.parse("testXML", JSON.stringify(elements)));
// });
// // console.log(JSON.stringify(finalJson));
// // console.log(js2xmlparser.parse("testXML", JSON(finalJson)));
